language: python
python:
  - "3.7"
services:
  - postgresql
install:
  - pip install -r requirements-travis.txt
before_script:
  - python manage.py collectstatic
script:
  - python manage.py test
env:
  - DJANGO_VERSION=2.1.7
deploy:
  provider: heroku
  api_key:
    secure: secure: "fgvrtW/CK/Rh/3YD+09Pb2pc7lhJOqvyVHvZIrdK5cyZtsSdD6a265lxoZaN+yde8JDALvlR5gQe4aRRocx3OP664yIy6EaWZI0PTsZMEPgAkd6eZJQf+kFVsQHYhh1m9CMOPi6FqQ6SSY3N8Y9IJdGwxvSrUL4bJb/0P47g7xlCXASqFkr+J8jW3a+M8iXifmXuFtziEsTRIKOHIaCt7uq37BEpaeI5oHMfF2v3muhONB2jblVou24JDZJzlwmnXEIl8WqsZFcAYsHVSvgWpkEsJg7aGE7hFmNtYg+kjVxJThbcHn9GOdKLtG8gv+mJEMQBR0iXKgy2GMR8iwxLfcg8AkHLPW9PuVqTtevyuj/Z5AdXO0uTEqayVBv+pZQ7HLbCDZ9vt3QxirQXrvbaEzhHoj/6e9PyMG2JTEprf0VngvtkZsEWl2d1wLduYjZFM+R9KXZSSnzpwqmm4ey3a3yn528FMvlBM+TYDGv+dWugOrW9kM2vK1awNx6HQamCVmGLaa68/JIgToviqb3iTC8XApm3Y674v7VAN7+m6z+V1GMUWAVCxIFGv8d3ZcDktSqeHVZYg/LeMXV5qEVj350bj/ogHmaXL1Zy5/F0YBV5oZ91wIteK36FVqsiZQz9WGmWL4Udm9cANGDlxLydp8CwnxNjugpFeYaJIIKaaAw="
  app: uvacraigslist
  on:
    repo: uva-cs3240-f19/project-102-supernovas