language: python
python:
  - "3.7"
services:
  - postgresql
install:
  - pip install -r requirements-travis.txt
before_script:
  - python manage.py collectstatic
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test
env:
  - DJANGO_VERSION=2.1.7
deploy:
  provider: heroku
  api_key:
    secure: "2a727f1a-4450-4e96-ba75-d94666b2b92d"
  app: project-102-supernovas
  on:
    repo: uva-cs3240-f19/project-102-supernovas