# Generated by Django 2.1.7 on 2019-11-11 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_price', models.IntegerField(default=0)),
                ('item_delivery', models.BooleanField(default=False)),
                ('item_photo', models.ImageField(default='static/marketplace/default.png', upload_to='media/')),
                ('item_location', models.CharField(max_length=200)),
                ('item_preferred_payment_method', models.CharField(choices=[('venmo', 'VENMO'), ('cash', 'CASH'), ('check', 'CHECK'), ('paypal', 'PAYPAL'), ('applePay', 'APPLEPAY'), ('none', 'NONE'), ('other', 'OTHER')], default='venmo', max_length=10)),
                ('item_condition', models.CharField(choices=[('new', 'NEW'), ('like new', 'LIKE NEW'), ('very good', 'VERY GOOD'), ('good', 'GOOD'), ('acceptable', 'ACCEPTABLE')], default='good', max_length=10)),
                ('item_sold', models.BooleanField(default=False)),
                ('item_categories', multiselectfield.db.fields.MultiSelectField(choices=[('furniture', 'FURNITURE'), ('textbooks', 'TEXTBOOKS'), ('clothing', 'CLOTHING'), ('class supplies', 'CLASS SUPPLIES'), ('kitchen', 'KITCHEN'), ('dorm', 'DORM'), ('uva gear', 'UVA GEAR'), ('electronics', 'ELECTRONICS'), ('other', 'OTHER')], max_length=83)),
                ('item_add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('latitude', models.FloatField(default=38.035618)),
                ('longitude', models.FloatField(default=-78.503415)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('text', models.CharField(max_length=250)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posRate', models.IntegerField(default=0)),
                ('negRate', models.IntegerField(default=0)),
                ('numTransactions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
