# Generated by Django 2.1.7 on 2019-09-24 02:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_price', models.IntegerField(default=0)),
                ('item_delivery', models.BooleanField(default=False)),
                ('item_location', models.CharField(max_length=200)),
                ('item_preferpay', models.CharField(choices=[('venmo', 'VENMO'), ('cash', 'CASH'), ('check', 'CHECK'), ('paypal', 'PAYPAL'), ('applePay', 'APPLEPAY'), ('none', 'NONE'), ('other', 'OTHER')], default='venmo', max_length=10)),
                ('item_condition', models.CharField(choices=[('new', 'NEW'), ('like new', 'LIKE NEW'), ('very good', 'VERY GOOD'), ('good', 'GOOD'), ('acceptable', 'ACCEPTABLE')], default='good', max_length=10)),
                ('item_sold', models.BooleanField(default=False)),
                ('item_categories', multiselectfield.db.fields.MultiSelectField(choices=[('furniture', 'FURNITURE'), ('textbooks', 'TEXTBOOKS'), ('clothing', 'CLOTHING'), ('class supplies', 'CLASS SUPPLIES'), ('kitchen', 'KITCHEN'), ('dorm', 'DORM'), ('uva gear', 'UVA GEAR'), ('electronics', 'ELECTRONICS'), ('other', 'OTHER')], max_length=14)),
                ('item_add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_computing_id', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Seller'),
        ),
    ]
