# Generated by Django 2.1.7 on 2019-11-11 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timesent',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='time sent'),
        ),
    ]
