# Generated by Django 2.1.7 on 2019-09-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_preferpay',
            new_name='item_preferred_payment_method',
        ),
    ]
