# Generated by Django 2.2.5 on 2019-11-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(default='C:\\Users\\richa\\OneDrive\\Documents\\GitHub\\project-102-supernovas\\static/marketplace/default.png', upload_to='images/'),
        ),
    ]
