# Generated by Django 2.2.5 on 2019-11-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(default='C:\\Users\\richa\\OneDrive\\Documents\\GitHub\\project-102-supernovas\\static/marketplace/default.png', upload_to='C:\\Users\\richa\\OneDrive\\Documents\\GitHub\\project-102-supernovas\\images/'),
        ),
    ]
