# Generated by Django 2.1.7 on 2019-10-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20191027_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_field', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bad_votes',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='good_votes',
        ),
        migrations.AddField(
            model_name='ratinginfo',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Seller'),
        ),
    ]
