# Generated by Django 2.1.7 on 2019-09-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190923_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
