# Generated by Django 2.1.7 on 2019-12-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_message_timesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_categories',
            field=models.CharField(choices=[('furniture', 'FURNITURE'), ('textbooks', 'TEXTBOOKS'), ('clothing', 'CLOTHING'), ('class supplies', 'CLASS SUPPLIES'), ('kitchen', 'KITCHEN'), ('dorm', 'DORM'), ('uva gear', 'UVA GEAR'), ('electronics', 'ELECTRONICS'), ('other', 'OTHER')], max_length=100),
        ),
    ]
