# Generated by Django 2.1.7 on 2019-12-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20191202_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_location',
        ),
    ]
