# Generated by Django 2.2.5 on 2019-11-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20191110_2051'),
        ('marketplace', '0004_auto_20191110_1712'),
    ]

    operations = [
    ]
