# Generated by Django 2.1.7 on 2019-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20191110_1712'),
        ('marketplace', '0002_auto_20191110_2051'),
    ]

    operations = [
    ]
