# Generated by Django 2.2.5 on 2019-11-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_merge_20191111_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=75)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
