# Generated by Django 2.1.7 on 2019-11-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0005_merge_20191111_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratinginfo',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='num_transactions',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_computing_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='negRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='numTransactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='posRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RatingInfo',
        ),
    ]
