# Generated by Django 2.1.7 on 2019-11-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20191111_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
