# Generated by Django 2.1.7 on 2019-11-11 13:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20191111_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('furniture', 'FURNITURE'), ('textbooks', 'TEXTBOOKS'), ('clothing', 'CLOTHING'), ('class supplies', 'CLASS SUPPLIES'), ('kitchen', 'KITCHEN'), ('dorm', 'DORM'), ('uva gear', 'UVA GEAR'), ('electronics', 'ELECTRONICS'), ('other', 'OTHER')], max_length=83),
        ),
    ]
