# Generated by Django 2.2.5 on 2019-11-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_message'),
        ('marketplace', '0008_auto_20191111_0856'),
    ]

    operations = [
    ]
